name: Trigger auto deployment for test123

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo TEST123
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/test123-AutoDeployTrigger-0beb1b19-ca7d-403a-9471-803189b2299a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TEST123_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TEST123_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TEST123_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image to ACR (if Dockerfile exists)
        uses: azure/acr-action@v1  # This step builds and pushes if Dockerfile present
        with:
          registry: axwaymanish.azurecr.io
          name: anm
          username: ${{ secrets.TEST123_REGISTRY_USERNAME }}
          password: ${{ secrets.TEST123_REGISTRY_PASSWORD }}

      - name: Deploy to Container App
        uses: Azure/container-apps-deploy-action@v1
        with:
          app-name: test123  # Replace with your app name
          resource-group: RG-mavishnoi
          image-source: acr  # Specify image source as ACR
          image-name: axwaymanish.azurecr.io/anm 
          


